### ISSUE TITLE
bradytachy test

### ISSUE THREAD

**Issue by epvienneau** [polortiz4/bme590_assignment02#52]
Mark- I would like to test my functions bradycardia and tachycardia with multiple inputs, eg test bradycardia once with a threshold of 60 and once with a threshold of 50, etc. I feel like there's a more elegant way to do that then simply calling bradycardia, making some asserts, and then copying and pasting that over and over again. Thoughts?
ps I will push my current bradytachy files to my branch (bradytachy) shortly

**Comment by mlp6** [comment]
You can create a loop in your testing function that sweeps across an array of threshold values and nest your `assert` statement within that loop.  Would that achieve what you want?

**Comment by epvienneau** [comment]
Yes! I was just wondering if there was some magical python thing I wasn't aware of (like np.where instead of my loop in bradytachy). Thanks!

**Comment by mlp6** [comment]
Nope - no magic on that one!
