### ISSUE TITLE
Permission Denied 

### ISSUE THREAD

**Issue by epvienneau** [polortiz4/bme590_assignment02#63]
So I was trying to run just one of my unit tests instead of doing py.test so I did `<chmod +x>` on the unit test file so I could run it, but now whenever I want to add it to git or run it through py.test I have to type `<sudo>` because it keeps saying permission denied... I tried changing the permission to read write execute and it's still not working. Haven't found anything helpful on google. Thoughts?

**Comment by mlp6** [comment]
What test were you trying to run?    Something doesn't sound right here...

**Comment by epvienneau** [comment]
I was just trying to run test_tachybradycardia.py

**Comment by mlp6** [comment]
Did you try: `python -m pytest test_tachybracdycardia.py`?  That should avoid needing to change any permissions and "executing" the test... this calls python and uses the pytest module to execute the contents of your specified file.

**Comment by epvienneau** [comment]
Wow ok thanks! lesson learned
